//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ClinicSystem.Infrastructure.Interfaces;

    public partial class ClinicSystemDbContext : DbContext, IClinicSystemDbContext
    {
        public ClinicSystemDbContext()
            : base("name=ClinicSystemDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASPNETROLES> ASPNETROLES { get; set; }
        public virtual DbSet<ASPNETUSERCLAIMS> ASPNETUSERCLAIMS { get; set; }
        public virtual DbSet<ASPNETUSERLOGINS> ASPNETUSERLOGINS { get; set; }
        public virtual DbSet<ASPNETUSERS> ASPNETUSERS { get; set; }
        public virtual DbSet<CLINIC> CLINIC { get; set; }
        public virtual DbSet<DIAGNOSTICS> DIAGNOSTICS { get; set; }
        public virtual DbSet<DISEASE> DISEASE { get; set; }
        public virtual DbSet<EMPLACEMENT> EMPLACEMENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<EMPLOYEE_COST> EMPLOYEE_COST { get; set; }
        public virtual DbSet<EXAMINATION> EXAMINATION { get; set; }
        public virtual DbSet<MEDICINE_ORDER> MEDICINE_ORDER { get; set; }
        public virtual DbSet<MEDICINE_TYPE> MEDICINE_TYPE { get; set; }
        public virtual DbSet<PATIENT_DIAGNOSE> PATIENT_DIAGNOSE { get; set; }
        public virtual DbSet<PATIENT_MEDICINES> PATIENT_MEDICINES { get; set; }
        public virtual DbSet<PATIENT_VISIT> PATIENT_VISIT { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<UNIT> UNIT { get; set; }
        public virtual DbSet<UNIT_PLAN> UNIT_PLAN { get; set; }
        public virtual DbSet<UNIT_TYPE> UNIT_TYPE { get; set; }
    }
}
