//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicSystemDbContext : DbContext
    {
        public ClinicSystemDbContext()
            : base("name=ClinicSystemDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<clinic> clinic { get; set; }
        public virtual DbSet<diagnostics> diagnostics { get; set; }
        public virtual DbSet<disease> disease { get; set; }
        public virtual DbSet<emplacement> emplacement { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_cost> employee_cost { get; set; }
        public virtual DbSet<examination> examination { get; set; }
        public virtual DbSet<medicine_order> medicine_order { get; set; }
        public virtual DbSet<medicine_type> medicine_type { get; set; }
        public virtual DbSet<patient_diagnose> patient_diagnose { get; set; }
        public virtual DbSet<patient_medicines> patient_medicines { get; set; }
        public virtual DbSet<patient_visit> patient_visit { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<unit> unit { get; set; }
        public virtual DbSet<unit_plan> unit_plan { get; set; }
        public virtual DbSet<unit_type> unit_type { get; set; }
    }
}
