//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICS
    {
        public long ID { get; set; }
        public System.DateTime LAST_MOD_DATE { get; set; }
        public System.DateTime EXAMINATION_DATE { get; set; }
        public long PATIENT_VISIT_ID { get; set; }
        public long EXAMINATION_ID { get; set; }
        public long UNIT_PLAN_ID { get; set; }
        public long EMPLOYEE_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EXAMINATION EXAMINATION { get; set; }
        public virtual PATIENT_VISIT PATIENT_VISIT { get; set; }
        public virtual UNIT_PLAN UNIT_PLAN { get; set; }
    }
}
