//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_cost
    {
        public long id { get; set; }
        public decimal employee_cost1 { get; set; }
        public System.DateTime realization_date { get; set; }
        public long employee_id { get; set; }
        public long unit_plan_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual unit_plan unit_plan { get; set; }
    }
}
