//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.DIAGNOSTICS = new HashSet<DIAGNOSTICS>();
            this.EMPLOYEE_COST = new HashSet<EMPLOYEE_COST>();
            this.EMPLOYEE1 = new HashSet<EMPLOYEE>();
        }
    
        public long ID { get; set; }
        public System.DateTime LAST_MOD_DATE { get; set; }
        public decimal SALARY { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public long PERSON_ID { get; set; }
        public long UNIT_ID { get; set; }
        public long EMPLACEMENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOSTICS> DIAGNOSTICS { get; set; }
        public virtual EMPLACEMENT EMPLACEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_COST> EMPLOYEE_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEE1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE2 { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
