//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_COST
    {
        public long ID { get; set; }
        public decimal EMPLOYEE_COST1 { get; set; }
        public System.DateTime REALIZATION_DATE { get; set; }
        public long EMPLOYEE_ID { get; set; }
        public long UNIT_PLAN_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual UNIT_PLAN UNIT_PLAN { get; set; }
    }
}
