//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicine_order()
        {
            this.patient_medicines = new HashSet<patient_medicines>();
        }
    
        public long id { get; set; }
        public decimal cost { get; set; }
        public System.DateTime epire_date { get; set; }
        public string seria { get; set; }
        public long medicine_type_id { get; set; }
    
        public virtual medicine_type medicine_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_medicines> patient_medicines { get; set; }
    }
}
