//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICINE_ORDER()
        {
            this.PATIENT_MEDICINES = new HashSet<PATIENT_MEDICINES>();
        }
    
        public long ID { get; set; }
        public System.DateTime LAST_MOD_DATE { get; set; }
        public decimal COST { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
        public string MEDICINE_BATCH_SERIES { get; set; }
        public long MEDICINE_TYPE_ID { get; set; }
    
        public virtual MEDICINE_TYPE MEDICINE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_MEDICINES> PATIENT_MEDICINES { get; set; }
    }
}
