//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_medicines
    {
        public long id { get; set; }
        public string dose { get; set; }
        public System.DateTime treatment_date { get; set; }
        public long patient_visit_id { get; set; }
        public long medicine_order_id { get; set; }
    
        public virtual medicine_order medicine_order { get; set; }
        public virtual patient_visit patient_visit { get; set; }
    }
}
