//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient_visit()
        {
            this.diagnostics = new HashSet<diagnostics>();
            this.patient_diagnose = new HashSet<patient_diagnose>();
            this.patient_medicines = new HashSet<patient_medicines>();
            this.patient_visit1 = new HashSet<patient_visit>();
        }
    
        public long id { get; set; }
        public System.DateTime date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public long person_id { get; set; }
        public Nullable<long> patient_visit_id { get; set; }
        public long clinic_id { get; set; }
        public long unit_id { get; set; }
    
        public virtual clinic clinic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diagnostics> diagnostics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_diagnose> patient_diagnose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_medicines> patient_medicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_visit> patient_visit1 { get; set; }
        public virtual patient_visit patient_visit2 { get; set; }
        public virtual person person { get; set; }
        public virtual unit unit { get; set; }
    }
}
