//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_VISIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT_VISIT()
        {
            this.DIAGNOSTICS = new HashSet<DIAGNOSTICS>();
            this.PATIENT_DIAGNOSE = new HashSet<PATIENT_DIAGNOSE>();
            this.PATIENT_MEDICINES = new HashSet<PATIENT_MEDICINES>();
        }
    
        public long ID { get; set; }
        public System.DateTime LAST_MOD_DATE { get; set; }
        public System.DateTime DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public long PERSON_ID { get; set; }
        public long CLINIC_ID { get; set; }
        public long UNIT_ID { get; set; }
    
        public virtual CLINIC CLINIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOSTICS> DIAGNOSTICS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_DIAGNOSE> PATIENT_DIAGNOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT_MEDICINES> PATIENT_MEDICINES { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
