//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSystem.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_diagnose
    {
        public long id { get; set; }
        public string diagnose { get; set; }
        public long patient_visit_id { get; set; }
        public long disease_id { get; set; }
    
        public virtual disease disease { get; set; }
        public virtual patient_visit patient_visit { get; set; }
    }
}
